### PR TITLE
Fix python extensions upload

### PR DESCRIPTION
**Pull request by dlopes7**
Python extensions are not built to workspaceStorage, so the upload fails because it can't find the zip file at the workspaceStorage.

The code is getting a bit messy, might want to have a different method that handles python extensions

I don't know how to add a test for this behavior quite yet, will research

### CODE REVIEW

**Comment by radu-stefan-dt** [comment]
It's not meant to build directly into workspace.

We're using the workspaceStorage (the VSCode provided storage for this workspace) to keep intermediary files and builds that have not been validated yet. Once validation passes, we move the .zip from that into the `dist` folder of the workspace.

This ensures only working builds are in your actual workspace. In the case of FastMode especially this is useful as you may have many broken builds along the way that we shouldn't keep.

**Comment by dlopes7** [comment]
Ok, so you are saying we should change the build command instead? Because upload is not working atm

**Comment by dlopes7** [comment]
@radu-stefan-dt can you take a look when you have some time, it has the changes we discussed yesterday:

- Python extensions are built to the temporary folder
- They are copied to the dist folder if validation passes (when not on fastmode)
- Variable names are kept the same as standard extensions
- Upload is not changed

**Review by radu-stefan-dt — CHANGES_REQUESTED** [review]
Could you please also correct the documentation string (line 220) to include the `workspaceStorage` variable? I'll merge it afterwards

**Comment by radu-stefan-dt** [comment]
Actually, that's fine, I'll fix the doc text myself when creating the next release.

**Review by radu-stefan-dt — APPROVED** [review]

**Pull request merged**
